### ISSUE TITLE
El tag <a> no encierra al texto correspondiente del video "How To Teach Yourself Code (ft. Quincy Larson)"

### ISSUE THREAD

**Issue by nhsz** [FreeCodeCampBA/wiki#3]
- El link al video "How To Teach Yourself Code (ft. Quincy Larson)" dentro de **Charlas Recomendadas** cierra antes del fragmento de texto, haciendo que el mismo no se comporte como un link. 

Ver [en la wiki](https://freecodecampba.org/wiki/).

**Comment by flopywood** [comment]
Modifique los links a las entrevistas a Quincy.

**Comment by nhsz** [comment]
Lo doy por solucionado.
