### ISSUE TITLE
The link for Image Hover Effects don't work

### ISSUE THREAD

**Issue by alebarbaja** [FreeCodeCampBA/wiki#9]
It leads to http://miketricking.github.io/dist/ but this web is not anymore online

<img width="215" alt="captura de pantalla 2018-05-19 a las 22 02 43" src="https://user-images.githubusercontent.com/28918805/40272607-68682424-5bb0-11e8-83c2-98106e4934f7.png">

<img width="855" alt="captura de pantalla 2018-05-19 a las 22 03 16" src="https://user-images.githubusercontent.com/28918805/40272612-796c55b0-5bb0-11e8-944a-fe207c962b5c.png">

**Comment by nhsz** [comment]
Hi @alebarbaja, thanks for reporting it. I just removed the link because the page now no longer exists.
